// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBliPfuV5AZX5STRBmyXmnvF4iT5AYeowo',
    appId: '1:198979800794:web:63b5b7dd33e62b632b5fe3',
    messagingSenderId: '198979800794',
    projectId: 'forest-mobile-ff440',
    authDomain: 'forest-mobile-ff440.firebaseapp.com',
    storageBucket: 'forest-mobile-ff440.appspot.com',
    measurementId: 'G-7XD8BGBB86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9IK5KK3wDQYowjPh7uBTCJK6wmtDwHEM',
    appId: '1:198979800794:android:d15a362b2d7bf5b72b5fe3',
    messagingSenderId: '198979800794',
    projectId: 'forest-mobile-ff440',
    storageBucket: 'forest-mobile-ff440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Zaa9QbbG7u_tpFN5iLjyda60Y2YQsD0',
    appId: '1:198979800794:ios:be3515178c66a1492b5fe3',
    messagingSenderId: '198979800794',
    projectId: 'forest-mobile-ff440',
    storageBucket: 'forest-mobile-ff440.appspot.com',
    iosBundleId: 'uz.devops.forestMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Zaa9QbbG7u_tpFN5iLjyda60Y2YQsD0',
    appId: '1:198979800794:ios:a2e13022a210f84d2b5fe3',
    messagingSenderId: '198979800794',
    projectId: 'forest-mobile-ff440',
    storageBucket: 'forest-mobile-ff440.appspot.com',
    iosBundleId: 'uz.devops.forestMobile.RunnerTests',
  );
}
